set encoding=utf-8
scriptencoding utf-8
set fileencodings=utf-8,cp932,sjis,utf-16le
set fileformats=unix,dos

syntax enable
"colorscheme quiet
colorscheme lunaperche
filetype plugin indent on

set number
set cursorline
set ruler
set title
set belloff=all
set mouse=a

set laststatus=2
set showcmd
set wildmenu
set wildmode=longest,full
set history=10000

set autoread
set noswapfile
set noundofile
set nobackup

set hidden

set ignorecase
set smartcase
set hlsearch
set incsearch
set wrapscan

set autoindent
set shiftwidth=0 softtabstop=0 tabstop=4 expandtab
set smartindent

let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_altv = 1
let g:netrw_browse_split = 4
let g:netrw_winsize = 75
let g:netrw_preview=1
"let g:netrw_browse_split = 2

set splitbelow
"set termwinsize=15x0

inoremap <C-j> <Down>
inoremap <C-k> <Up>
inoremap <C-h> <Left>
inoremap <C-l> <Right>

inoremap <silent> jj <ESC>

nnoremap <ESC><ESC> :nohlsearch<CR>
nnoremap <Leader>vim :e ~/.vimrc<CR>
